language: python
deploy:
  provider: heroku
  api_key:
    secure: QF1+ts0IEXXi4xhEoaBVUhLOx7GkKit38uNgrtoFBASlfCYarExikLj9TCG3gEzzh1EWZBhtSm1e7iI/qKOzE7KplA2TEeJOB9rFrlhe1D1u99JHzmzE3UgbrDCqjAdON2oefXlRZ+tiIlFBXXYEsahSL6XlSOg/f88PBDiC3ZWM+XEgpzJEhOo4xJ/hl3AC+VtHitIJb9LvereLtzdlqbmLtpZjvW7qcoNCCWWJKl0MedOx9aV7zH14twH7Hupi7k2mv+NkrLsJrs/wDrTwLz6NUOcns6BreC/aqgAL6tGGy7nrFkhaEroiNqR1Fn4fEDB6u557rcPdAlyFG0KM+wUAetrfYbaH6lIEWwXpkOKp47EY+xYFYpXSlBR6e4dXGw/zcvcgFscL7rgXxXzbi2sWXMNMPzwtDKMXkc0wJ+MCEi4/TgdruKB9m8EjYATmDNWNvQHAD0iLS1N+Wt3AmFgogqf4Xhk3P4h707PxIP6oPBuOhPjcA+U5ODqVU2fl5dQnAqXE3E8O+0raavvPRv2tcBKLwH3YgkRc14x79/XyWApiiIYl6wApVePTGZMvTn0RSgNp7hW+CD79qmQK5DB5NQnzTKD/cbdrMFG5LUu7H5SVrPDiluUFPfmalCzjkIAp7Oy8xaQ17fJQu8fVVrAlSjmvJpc9NFRRwUio+2s=
  app: gcstravis
  on:
    repo: rafaelrabetti/GCS
script:
- python manage.py migrate
- python manage.py test
- flake8 --exclude polls/migrations/,manage.py  .
