language: python
deploy:
  provider: heroku
  api_key:
    secure: e0ee41a1-482c-48d8-95c9-3bf1b8b6ddf5
  app: gcs01-rafaelrabetti-travis
  on:
    repo: rafaelrabetti/GCS
script:
- python manage.py migrate
- python manage.py test
- flake8 --exclude polls/migrations/,manage.py  .
